name: Cypress Test Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: setup local server
        run: start npm start
      - name: Run Cypress tests
        run: npm run cypress